### ISSUE TITLE
Pasted key loses original's Key Style.

### ISSUE THREAD

**Issue by joao7yt** [ThoNohT/NohBoard#37]
The cloned key has the default Key Style.

**Comment by ThoNohT** [comment]
Fixed in 01b1254c2d7b6482a6aaaa5d314336f688b51685

**Comment by joao7yt** [comment]
well, i think it's not fixed, watch this video: https://youtu.be/FnoFxz2viJ8

**Comment by ThoNohT** [comment]
It worked for some, but apparently not for others. I'll re-open.

**Comment by ThoNohT** [comment]
By the way, feel free to reopen if an issue I close is clearly not fixed.

**Comment by ThoNohT** [comment]
Should now be fixed with 3537c2c57a37d80bc321c291bf241bd49d3744f6

**Comment by joao7yt** [comment]
almost all working fine, the problem i found now is that if you increase the keyboard workspace, you can't past a key in the new area available

**Comment by ThoNohT** [comment]
And that should be fixed in 56e7b98b74f82082de1aef3f72b7006b4d923e3a.
